### ISSUE TITLE
 Error: Encountered error on 71.XX.XXX.XXX:28965

### ISSUE THREAD

**Issue by 16BitShooter** [RaidMax/IW4M-Admin#13]
I'm not very sure that the issue is, I'm no coder so I thought you could help!
The server using IW4M is an IW4X (MW2) server. It does not appear to mess with the base server, it just makes the auto messages appear twice when sent...
This "error" constantly repeats in my powershell. In the logs I get this repeating over and over:

[18:43:06] - Error: Encountered error on 71.xx.xxx.xxx:28965
[18:43:06] - Debug: Error Message: Unexpected status response received
[18:43:06] - Debug: Error Trace:    at Application.RconParsers.IW4RConParser.ClientsFromStatus(String[] Status)
   at Application.RconParsers.IW4RConParser.<GetStatusAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IW4MAdmin.IW4MServer.<PollPlayersAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IW4MAdmin.IW4MServer.<ProcessUpdatesAsync>d__17.MoveNext()

Along with that bit I also had an odd encounter with the Welcome Plugin. Once again I'm not a coder, it would probably make our lives easier if I was....

[18:09:59] - Error: The plugin "Welcome Plugin" generated an error. ( see log )
[18:09:59] - Debug: Error Message: Value was either too large or too small for an unsigned byte.
[18:10:00] - Debug: Error Trace:    at System.Convert.ThrowByteOverflowException()
   at System.Convert.ToByte(Char value)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at SharedLibraryCore.RCon.Connection.<SendQueryAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Application.RconParsers.IW4RConParser.<ExecuteCommandAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SharedLibraryCore.Server.<Tell>d__13.MoveNext()

Thanks for any help you can provide, I'll keep an eye on this post for a few days!

**Comment by RaidMax** [comment]
Which version are you using? 2.0 or 2.1 pre-release? There was an issue with packets from the server coming back out of order, which resulted in that error. It's fixed in the 2.1 pre-release. I'd recommend you'd try the latest prerelease (at this time) frome https://raidmax.org/IW4MAdmin/Download/IW4MAdmin-2.1-prerelease5.zip

Let me know if you continue to have issues.

**Comment by 16BitShooter** [comment]
yes sir, that has fixed it as far as I can see. Also another question, where are all the stats and stuff like that kept? Are they in the individual plugins or are they all stored in one place? People might be a bit concerned when they find their stats aren't there lol.

**Comment by RaidMax** [comment]
If using SQLite (default database provider) everything (non configuration related) is stored in Database.db. If using a MySQL it is of course stored in the MySQL server.
