### ISSUE TITLE
FTL error

### ISSUE THREAD

**Issue by SlayerrGX** [RaidMax/IW4M-Admin#281]
Hello
am having this error and idk whats the fix for it

Not monitoring server due to uncorrectable errors [127.0.0.1:4977]
[2023-02-28 16:08:31.371  FTL] Failed to initialize IW4MAdmin
SharedLibraryCore.Exceptions.DvarException: Could not get the dvar value for fs_localAppData
   at IW4MAdmin.Application.ApplicationManager.InitializeServers()
   at IW4MAdmin.Application.ApplicationManager.Init()
   at IW4MAdmin.Application.Program.LaunchAsync(String[] args)
Fatal error during initialization
Could not get the dvar value for fs_localAppData
Press enter to exit...
Shutdown complete

can you help me?

**Comment by RaidMax** [comment]
Issues are not the place for support. Please join the [discord ](https://discord.gg/ZZFK5p3)for support
