### ISSUE TITLE
[BUG] A lot of errors in log... 

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#29]
https://pastebin.com/MxS4HrNB

Main errors are...

```
[08.27.2018 22:21:14.350] - Error: Unexpected exception on 195.154.102.115:28963
[08.27.2018 22:21:14.351] - Debug: Error Message: One or more errors occurred. (Sequence contains no elements)
[08.27.2018 22:21:14.352] - Debug: Error Trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at IW4MAdmin.IW4MServer.<>c.<InitializeTokens>b__21_2(Server s)
   at SharedLibraryCore.Helpers.MessageToken.Process(Server server)
   at SharedLibraryCore.Utilities.ProcessMessageToken(Server server, IList`1 tokens, String str)
   at IW4MAdmin.IW4MServer.ProcessUpdatesAsync(CancellationToken cts)
```
```
[08.27.2018 21:24:04.464] - Debug: Log detected Crappy Yard::-696819893583376794 joining
[08.27.2018 21:24:13.536] - Debug: Client slot #7 now reserved
[08.27.2018 21:24:13.540] - Debug: Client Crappy Yard::-696819893583376794 first time connecting
[08.27.2018 21:24:13.555] - Debug: Kicking Crappy Yard::-696819893583376794 their spot is reserved
[08.27.2018 21:24:13.555] - Error: Unable to add player Crappy Yard::-696819893583376794
[08.27.2018 21:24:13.556] - Debug: Invalid locale key SERVER_KICK_SLOT_IS_RESERVED
[08.27.2018 21:24:13.556] - Debug:    at SharedLibraryCore.Localization.Index.get_Item(String key)
   at IW4MAdmin.IW4MServer.AddPlayer(Player polledPlayer)
```
```
[08.27.2018 22:28:28.072] - Error: A plugin generated an error [Simple Stats]
[08.27.2018 22:28:28.073] - Debug: Error Message: The given key '1073' was not present in the dictionary.
[08.27.2018 22:28:28.074] - Debug: Error Trace:    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNotFoundException(Object key)
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at IW4MAdmin.Plugins.Stats.Helpers.StatManager.SetTeamBased(Int32 serverId, Boolean isTeamBased)
   at IW4MAdmin.Plugins.Stats.Plugin.OnEventAsync(GameEvent E, Server S)
   at IW4MAdmin.IW4MServer.ExecuteEvent(GameEvent E)
```
```
[08.27.2018 22:23:56.469] - Error: Unexpected exception on 195.154.102.115:28963
[08.27.2018 22:23:56.469] - Debug: Error Message: One or more errors occurred. (DVAR "sv_mapRotation" does not exist)
[08.27.2018 22:23:56.470] - Debug: Error Trace:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at IW4MAdmin.IW4MServer.<>c.<InitializeTokens>b__21_2(Server s)
   at SharedLibraryCore.Helpers.MessageToken.Process(Server server)
   at SharedLibraryCore.Utilities.ProcessMessageToken(Server server, IList`1 tokens, String str)
   at IW4MAdmin.IW4MServer.ProcessUpdatesAsync(CancellationToken cts)
```

`[08.27.2018 22:20:49.216] - Debug: Delaying origin execution of event type Command for Fz Amos::1843397405494546423 because they are not authed` ?? -- I logged in as 'Owner'...?

**Comment by RaidMax** [comment]
I've ben working on rewriting a lot of event management, I'll be pushing an update soon, that should fix most of these issues!

**Comment by RaidMax** [comment]
It’s close to being finished so hopefully I can release today.

**Comment by MrAmos123** [comment]
No rush man, I find it astounding you put this much effort into a side-project.

**Comment by MrAmos123** [comment]
@RaidMax Will your rework fix the fact that when I ban people they can rejoin and nothing from then will work?

https://i.imgur.com/YIACWKE.jpg

See this image, tried kicking in-game and on the console, but as I already banned him in-game he's able to roam freely and cheat his dick off... This is annoying because some of them trash talk and I literally cannot do anything to get rid of them.

**Comment by RaidMax** [comment]
Yes. It's 99% of the way ready. I just have to finish one last thing. I would highly recommend using pre-release 3 until I release.

**Comment by RaidMax** [comment]
Finally traced back the issue to a bug with the way IW4x prints out the log. Completed code and running stability tests overnight before releasing.
