### ISSUE TITLE
Linux ARM64 SQLite 3 library not included

### ISSUE THREAD

**Issue by Snivine** [RaidMax/IW4M-Admin#312]
as stated in the title, the SQLite 3 library for Linux ARM64 is not included in the release, making it so that the program throws this exception when trying to run it under arm64

```
[2023-10-13 20:57:46.965  FTL] Failed to initialize IW4MAdmin
System.TypeInitializationException: The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libe_sqlite3: cannot open shared object file: No such file or directory
   at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
   at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
   at SQLitePCL.Batteries_V2.Init()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Data.Sqlite.Utilities.BundleInitializer.Initialize()
   at Microsoft.Data.Sqlite.SqliteConnection..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Data.Sqlite.SqliteConnection..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteRelationalConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at Data.Context.ContextSeed.<>c__DisplayClass0_0.<<Seed>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Data.Context.ContextSeed.Seed(IDatabaseContextFactory contextFactory, CancellationToken token)
   at Data.Context.ContextSeed.Seed(IDatabaseContextFactory contextFactory, CancellationToken token)
   at IW4MAdmin.Application.ApplicationManager.Init()
   at IW4MAdmin.Application.Program.LaunchAsync()
Fatal error during initialization
Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libe_sqlite3: cannot open shared object file: No such file or directory
```

I understand that the games may not run in arm64 (but in my case I do run them under arm64 thanks to box86/64, so it would be nice if the arm64 lib was included

**Comment by RaidMax** [comment]
While ARM64 is not one of the platforms IW4MAdmin is distributed for, you should be able to add this library to `runtimes/linux-arm64/native`
[libe_sqlite3.zip](https://github.com/RaidMax/IW4M-Admin/files/12910401/libe_sqlite3.zip)
And proceed

**Comment by Snivine** [comment]
yeah that's exactly what I did and it works, but it would be nice if it's included in the releases, that's all

**Comment by diamante0018** [comment]
> yeah that's exactly what I did and it works, but it would be nice if it's included in the releases, that's all

You were informed that arm64 is not one of the platforms IW4M is distributed for. Why continue with the request?

**Comment by RaidMax** [comment]
Closing this as arm64 is not one of the planned supported platforms due to essentially non existent demand. Will leave this available for anyone that wants to tinker
