### ISSUE TITLE
[BUG] No VPN Kicking

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#35]
Joined via VPN with below account, and it doesn't kick me. :(
```
[09.02.2018 00:18:43.946] - Debug: Client Big Dick Dan::7837307843100953456 first time connecting
[09.02.2018 00:18:43.966] - Info: Client Big Dick Dan::7837307843100953456 connected...
[09.02.2018 00:18:43.989] - Debug: Calculating standard kill
[09.02.2018 00:18:44.078] - Debug: PredictVsReal=0.061
[09.02.2018 00:18:44.079] - Debug: Current Strain: 0.00630946682090703
[09.02.2018 00:18:44.115] - Error: A plugin generated an error [VPN Kick Plugin]
[09.02.2018 00:18:44.116] - Debug: Error Message: event is not defined
[09.02.2018 00:18:44.116] - Debug: Error Trace:    at Jint.Engine.Execute(Program program)
   at SharedLibraryCore.ScriptPlugin.OnEventAsync(GameEvent E, Server S)
   at IW4MAdmin.IW4MServer.ExecuteEvent(GameEvent E)
```
Maybe this will help figure out issue, I'm in the kicking exemption IDs:
```
[09.02.2018 00:15:31.740] - Info: Client Fz Amos::1843397405494546423 connected...
[09.02.2018 00:15:31.828] - Info: Client AUN::5252712073660470461 connected...
[09.02.2018 00:15:32.035] - Error: A plugin generated an error [VPN Kick Plugin]
[09.02.2018 00:15:32.035] - Debug: Error Message: An item with the same key has already been added. Key: System.Net
[09.02.2018 00:15:32.102] - Debug: Error Trace:    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Jint.Runtime.Interop.NamespaceReference.GetPath(String path)
   at Jint.Runtime.Interop.NamespaceReference.Get(String propertyName)
   at Jint.Engine.GetValue(Object value, Boolean returnReferenceToPool)
   at Jint.Runtime.ExpressionInterpreter.EvaluateMemberExpression(MemberExpression memberExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateMemberExpression(MemberExpression memberExpression)
   at Jint.Runtime.ExpressionInterpreter.EvaluateNewExpression(NewExpression newExpression)
   at Jint.Runtime.StatementInterpreter.ExecuteVariableDeclaration(VariableDeclaration statement)
   at Jint.Runtime.StatementInterpreter.ExecuteMultipleStatements(List`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(List`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteTryStatement(TryStatement tryStatement)
   at Jint.Runtime.StatementInterpreter.ExecuteMultipleStatements(List`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(List`1 statementList)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteSingleStatement(Statement s)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(List`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteIfStatement(IfStatement ifStatement)
   at Jint.Runtime.StatementInterpreter.ExecuteSingleStatement(Statement s)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(List`1 statementList)
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Jint.Runtime.ExpressionInterpreter.EvaluateCallExpression(CallExpression callExpression)
   at Jint.Engine.ExecuteStatement(Statement statement)
   at Jint.Runtime.StatementInterpreter.ExecuteSingleStatement(Statement s)
   at Jint.Runtime.StatementInterpreter.ExecuteStatementList(List`1 statementList)
   at Jint.Runtime.StatementInterpreter.ExecuteProgram(Program program)
   at Jint.Engine.Execute(Program program)
   at Jint.Engine.Execute(String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String source)
   at SharedLibraryCore.ScriptPlugin.OnEventAsync(GameEvent E, Server S)
   at IW4MAdmin.IW4MServer.ExecuteEvent(GameEvent E)
[09.02.2018 00:15:32.690] - Info: Adding Fz Amos::1843397405494546423 to stats
[09.02.2018 00:15:32.899] - Info: Adding AUN::5252712073660470461 to stats
```
There's also a lot of spam...
```
[09.02.2018 00:19:05.921] - Debug: PredictVsReal=0.329
[09.02.2018 00:19:05.921] - Debug: Current Strain: 0.00025924961302169
[09.02.2018 00:19:05.937] - Debug: PredictVsReal=0.329
[09.02.2018 00:19:05.937] - Debug: Current Strain: 0.00025921823860047
[09.02.2018 00:19:06.254] - Debug: PredictVsReal=0
[09.02.2018 00:19:06.254] - Debug: Current Strain: 0.0666453087102638
[09.02.2018 00:19:06.269] - Debug: PredictVsReal=0
[09.02.2018 00:19:06.269] - Debug: Current Strain: 0.000199228961832055
[09.02.2018 00:19:06.284] - Debug: PredictVsReal=0.44
[09.02.2018 00:19:06.285] - Debug: Current Strain: 0.000881851859405086
[09.02.2018 00:19:06.295] - Debug: Calculating standard kill
[09.02.2018 00:19:06.327] - Debug: PredictVsReal=0.242
[09.02.2018 00:19:06.327] - Debug: Current Strain: 0.00309455843563376
[09.02.2018 00:19:06.343] - Debug: PredictVsReal=0.242
[09.02.2018 00:19:06.343] - Debug: Current Strain: 0.00309418393177735
[09.02.2018 00:19:06.660] - Debug: PredictVsReal=0
[09.02.2018 00:19:06.660] - Debug: Current Strain: 0.00158516457056025
[09.02.2018 00:19:06.675] - Debug: PredictVsReal=0.1538
[09.02.2018 00:19:06.675] - Debug: Current Strain: 0.00509656925529465
[09.02.2018 00:19:06.686] - Debug: Calculating standard kill
[09.02.2018 00:19:06.718] - Debug: PredictVsReal=0
[09.02.2018 00:19:06.719] - Debug: Current Strain: 0.00898598594486651
[09.02.2018 00:19:06.734] - Debug: PredictVsReal=0
[09.02.2018 00:19:06.734] - Debug: Current Strain: 0.00898489845970182
[09.02.2018 00:19:07.352] - Debug: PredictVsReal=0
[09.02.2018 00:19:07.352] - Debug: Current Strain: 0.0353388837215023
[09.02.2018 00:19:07.362] - Debug: Calculating standard kill
[09.02.2018 00:19:07.394] - Debug: PredictVsReal=0.072
[09.02.2018 00:19:07.395] - Debug: Current Strain: 0.0365872902524896
[09.02.2018 00:19:07.410] - Debug: PredictVsReal=0.072
[09.02.2018 00:19:07.410] - Debug: Current Strain: 0.0365828624539587
[09.02.2018 00:19:08.027] - Debug: PredictVsReal=0.033
[09.02.2018 00:19:08.027] - Debug: Current Strain: 0.0183489815046544
[09.02.2018 00:19:08.042] - Debug: PredictVsReal=0
[09.02.2018 00:19:08.043] - Debug: Current Strain: 0.0334208161958384
[09.02.2018 00:19:08.960] - Debug: PredictVsReal=0
[09.02.2018 00:19:08.960] - Debug: Current Strain: 0.00115563075040223
[09.02.2018 00:19:09.276] - Debug: PredictVsReal=0.1813
[09.02.2018 00:19:09.276] - Debug: Current Strain: 0.00822406934480962
[09.02.2018 00:19:09.592] - Debug: PredictVsReal=0
[09.02.2018 00:19:09.593] - Debug: Current Strain: 0.0604569010014516
[09.02.2018 00:19:09.602] - Debug: Calculating standard kill
[09.02.2018 00:19:09.635] - Debug: PredictVsReal=0
[09.02.2018 00:19:09.635] - Debug: Current Strain: 0.0359577808115591
[09.02.2018 00:19:09.946] - Debug: Calculating standard kill
[09.02.2018 00:19:09.978] - Debug: PredictVsReal=0.0879
[09.02.2018 00:19:09.979] - Debug: Current Strain: 0.0625744688004295
[09.02.2018 00:19:09.994] - Debug: PredictVsReal=0.0879
```

**Comment by RaidMax** [comment]
The information at the end is because of the stats plugin being debug build. The mode I select is pretty unreliable for some reason when publishing

**Comment by RaidMax** [comment]
Re download the zip file and replace Stats.dll
