### ISSUE TITLE
I have an Issue

### ISSUE THREAD

**Issue by 16BitShooter** [RaidMax/IW4M-Admin#7]
I've followed the instructions as they were given, but when I launch iw4m admin this happens:
![error1](https://user-images.githubusercontent.com/31642248/30044814-cc3cfab8-91cd-11e7-833e-8d2078feb066.PNG)
TO CLARIFY: it connects to my server fine then I get the error
this happens when a client enters the server. here are my logs:
![error2](https://user-images.githubusercontent.com/31642248/30044856-21be7282-91ce-11e7-80f5-6609949b8530.PNG)

it constantly repeats this:
[00:17:22] - Debug: Error Message: Object reference not set to an instance of an object.
[00:17:22] - Debug: Error Trace:    at Welcome_Plugin.Plugin.<>c__DisplayClass11_0.<OnTickAsync>b__0(Player p)
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at Welcome_Plugin.Plugin.<OnTickAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at IW4MAdmin.IW4MServer.<ProcessUpdatesAsync>d__17.MoveNext()

Not sure whats causing the problem could be something so easy and I am just blind. 
I did try a few things on my own, I removed the welcome plugin and the problem was resolved. 
thought it would be good to let you know :)

BTW I won't be able to come back to this until 9/6 @ 4:00 PM est

when the map changed the same thing happened. This time the logs gave a different error:

[00:40:16] - Debug: Error Message: Server is RCON throttled
[00:40:16] - Debug: Error Trace:    at SharedLibrary.Network.RCON.<GetStatusAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IW4MAdmin.IW4MServer.<PollPlayersAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IW4MAdmin.IW4MServer.<ProcessUpdatesAsync>d__17.MoveNext()

thanks for any and all help :)

**Comment by RaidMax** [comment]
I'm looking into this now. Did you compile yourself or are you using the nightly build?

**Comment by RaidMax** [comment]
Actually, looking at the error message, it looks like you are using the "stable" build. I believe I prematurely pushed that code due to a release configuration error. Try using the latest nightly build and let me know if your issue persists. I've also republished the 1.4 Stable build.

**Comment by 16BitShooter** [comment]
I am using 1.4 currently, it seems along with the first issue the map changing thing still happens...

**Comment by RaidMax** [comment]
Are you sure you've overwritten the files?
`[00:40:16] - Debug: Error Message: Server is RCON throttled`
That error message no longer exists in the codebase.

**Comment by RaidMax** [comment]
As I have not heard back from you, I will assume this is fixed. Let me know if any further issues.
