### ISSUE TITLE
IndexOutOfRangeException on command validation

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#70]
```log
[03.17.2019 21:51:40.973] - Debug: Exception[0] Name: System.IndexOutOfRangeException
Exception[0] Message: Index was outside the bounds of the array.
Exception[0] Call Stack:    at SharedLibraryCore.Commands.CommandProcessing.ValidateCommand(GameEvent E)
   at IW4MAdmin.IW4MServer.ExecuteEvent(GameEvent E)
   at IW4MAdmin.Application.ApplicationManager.OnGameEvent(Object sender, GameEventArgs args)
Exception[0] Source: SharedLibraryCore
```
Command: `!votekick`
Expectation: `Usage: !votekick Player [Reason]`
Reality: -

Definition:
```cs
public Kick() : base(Kick._Name, "Starts a vote to remove a player", Kick._Alias, EFClient.Permission.User, true, new CommandArgument[] { new CommandArgument { Name = "Reason", Required = false}})
        {
            //CTOR
        }
```

**Comment by RaidMax** [comment]
fixed in 52b15e5
